### ISSUE TITLE
Error on some VK codes

### ISSUE THREAD

**Issue by howardjohn** [howardjohn/pyty#10]
Noticed on UP, DOWN, ENTER so far. 
`Traceback (most recent call last):
  File "pyty.py", line 9, in <module>
    HOOK_MANAGER = HookManager(WINDOW_MANAGER)
  File "D:\dev\Self\pyty\src\hook_manager.py", line 54, in __init__
    ghk.listen()
  File "D:\dev\Self\pyty\src\global_hotkeys.py", line 58, in listen
    str(ctypes.windll.kernel32.GetLastError()))
Exception: Unable to register hot key: 13 error code is: 1409
`

**Comment by howardjohn** [comment]
Also noted with SPACE.
Using ALTMOD resolves this issue -- maybe overlapping hotkeys with another program?

**Comment by howardjohn** [comment]
Definitive cause is already hooked by another program -- Unhooked keys with win+shift+LETTER will print letter, hooked ones will not. Also happens with M. Unsure which program is causing hooks
